[project]
authors = ["Farnoosh Babazadeh <farnooshbabazadeh@gmail.com>"]
channels = ["conda-forge"]
description = "Differential expression analysis using Immuno-Oncology RNA-seq clinical data"
name = "genome-analytics"
platforms = ["win-64"]
version = "0.1.0"

[dependencies]
python = "3.10"
numpy = ">=1.24,<1.27"
matplotlib = ">=3.7,<3.9"
scikit-learn = ">=1.2,<1.4"
pandas = ">=2.0,<2.3"
scipy = "1.11.0"
anndata = "0.8.0"
jupyter = "*"
pip = "*"

[pypi-dependencies]
pydeseq2 = ">=0.5.0"
