[project]
authors = ["Farnoosh Babazadeh <farnooshbabazadeh@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "genome-analytics"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
